# Generated by Django 2.2.7 on 2020-08-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200730_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
