# Generated by Django 2.2.7 on 2020-08-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_reviews_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
