# Generated by Django 2.2.7 on 2020-08-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.RatingStart', verbose_name='Звезда'),
            preserve_default=False,
        ),
    ]
