# Generated by Django 2.2.7 on 2020-08-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_reviews_star'),
    ]

    operations = [
    ]
