# Generated by Django 2.2.7 on 2020-08-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_20200820_2313'),
        ('users', '0017_reviews_star'),
    ]

    operations = [
    ]
