# Generated by Django 2.2.7 on 2020-08-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200807_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщении'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
