# Generated by Django 2.2.7 on 2020-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200811_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='thread',
            name='new_messages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Непрочитанные сообщения'),
        ),
    ]
