# Generated by Django 2.2.7 on 2020-08-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_chatmessage_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
    ]
