# Generated by Django 2.2.7 on 2020-08-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_filemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rooms.ChatMessage', verbose_name='Сообщении'),
        ),
    ]
