# Generated by Django 2.2.7 on 2020-08-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200816_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
