# Generated by Django 2.2.7 on 2020-08-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200818_1715'),
        ('rooms', '0011_chatmessage_status'),
    ]

    operations = [
    ]
