# Generated by Django 2.2.7 on 2020-08-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='informations.PhonesInfo', verbose_name='Номер телефона'),
        ),
    ]
