# Generated by Django 2.2.7 on 2020-08-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_auto_20200811_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='phonesinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='informations.ContactInfo', verbose_name='Адрес'),
        ),
    ]
