# Generated by Django 2.2.7 on 2020-08-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_auto_20200811_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='informations.ContactInfo', verbose_name='Адрес'),
        ),
    ]
