# Generated by Django 2.2.7 on 2020-08-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_messages', models.IntegerField(blank=True, null=True, verbose_name='Непрочитанные сообщения')),
                ('time', models.IntegerField(default=0, verbose_name='Время чата')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_first', to=settings.AUTH_USER_MODEL, verbose_name='Первый пользователь')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_second', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audio-file/', verbose_name='Аудио')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/image-file/', verbose_name='Картинки')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/video-file/', verbose_name='Видео')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communication.Thread', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
    ]
