# Generated by Django 2.2.7 on 2020-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='times_rooms',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания чата'),
        ),
    ]
