# Generated by Django 2.2.7 on 2020-09-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='times_rooms',
        ),
    ]
