# Generated by Django 2.2.7 on 2020-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20200902_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/file/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='thread',
            name='times_rooms',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания чата'),
        ),
    ]
