# Generated by Django 2.2.7 on 2020-09-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_auto_20200730_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
